### PR TITLE
added park, post and address model

### PR DESCRIPTION
**Pull request by hey-chan**

### CODE REVIEW

**Review by leberSmeaton — COMMENTED** [review]
This is pretty close to the ERD. I do think there are some references we need to discuss further before the merge, maybe an update is required on the parks model. Otherwise I'd say all that's needed next is the image connections to AWS.

**Comment by hey-chan** [comment]
I've added the association between model. Might be good to check it out. Possibly missed something, I'm not sure

**Comment by hey-chan** [comment]
Also added migrations for parks model. Latitude and longitude are floats

**Review by leberSmeaton — APPROVED** [review]
Merging with suggested update for next feature:
create parks references need to be shifted.

**Pull request merged**
